// This file belongs to the trace projection layer.
// It owns run-inspection projection for this package.
// It projects runtime evidence; it must not change execution decisions.
package tracing

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// RunInspection is the frontend debugging contract for one chat turn.
//
// It is derived from TurnTrace but intentionally exposes only whitelisted
// attributes so the chat UI can diagnose execution without leaking raw prompts,
// full user input, or long model outputs.
type RunInspection struct {
	TraceID     string          `json:"trace_id"`
	SessionID   string          `json:"session_id"`
	Status      string          `json:"status"`
	TurnType    string          `json:"turn_type"`
	TotalMs     int64           `json:"total_ms"`
	Summary     RunSummary      `json:"summary"`
	Diagnostics []RunDiagnostic `json:"diagnostics"`
	Spans       []RunSpan       `json:"spans"`
}

// RunSummary contains the high-signal route/runtime facts shown in the
// collapsed Run Inspector header.
type RunSummary struct {
	PrimaryDomain  string `json:"primary_domain,omitempty"`
	TaskIntent     string `json:"task_intent,omitempty"`
	DecisionSource string `json:"decision_source,omitempty"`
	GateReason     string `json:"gate_reason,omitempty"`
	InspectionText string `json:"inspection_text"`
}

// RunDiagnostic is one deterministic finding that tells the UI where to look
// next. These findings are generated by code, not by an LLM.
type RunDiagnostic struct {
	Severity   string   `json:"severity"`
	Stage      string   `json:"stage"`
	Code       string   `json:"code"`
	Title      string   `json:"title"`
	Evidence   []string `json:"evidence,omitempty"`
	NextAction string   `json:"next_action,omitempty"`
	SpanID     string   `json:"span_id,omitempty"`
}

// RunSpan is the safe frontend projection of one TraceSpan.
type RunSpan struct {
	SpanID       string         `json:"span_id"`
	ParentSpanID string         `json:"parent_span_id,omitempty"`
	Name         string         `json:"name"`
	Label        string         `json:"label"`
	Kind         string         `json:"kind"`
	Category     string         `json:"category"`
	Status       string         `json:"status"`
	DurationMs   int64          `json:"duration_ms"`
	Error        string         `json:"error,omitempty"`
	Attributes   map[string]any `json:"attributes,omitempty"`
}

var runInspectionAttrWhitelist = map[string]struct{}{
	"artifact_present":                   {},
	"bazi.contract.failure_class":        {},
	"bazi.contract.finding_code":         {},
	"bazi.contract.recovery_policy":      {},
	"bazi.dynamic.source":                {},
	"bazi.final.audit_result":            {},
	"bazi.final.output_mode":             {},
	"bazi.internal_graph.node":           {},
	"bazi.internal_graph.path":           {},
	"bazi.internal_graph.recovery_state": {},
	"bazi.static.source":                 {},
	"conversation_intent":                {},
	"degrade_reason":                     {},
	"degraded":                           {},
	"decision_source":                    {},
	"dispatch_domains":                   {},
	"dispatch_owner":                     {},
	"domains":                            {},
	"event_type":                         {},
	"failure.class":                      {},
	"failure.code":                       {},
	"failure.degraded":                   {},
	"failure.retryable":                  {},
	"failure.stage":                      {},
	"filter":                             {},
	"final_text_len":                     {},
	"followup_mode":                      {},
	"forced_route":                       {},
	"gate.execution_mode":                {},
	"gate.followup_policy":               {},
	"gate.reason":                        {},
	"gen_ai.operation.name":              {},
	"gen_ai.request.model":               {},
	"gen_ai.usage.input_tokens":          {},
	"gen_ai.usage.output_tokens":         {},
	"guardrail_result":                   {},
	"hits":                               {},
	"input.message_count":                {},
	"input.message_roles":                {},
	"inner_graph":                        {},
	"model":                              {},
	"needs_clarification":                {},
	"output_tokens":                      {},
	"primary_domain":                     {},
	"query":                              {},
	"qimen_mode":                         {},
	"repair.action":                      {},
	"repair.attempt":                     {},
	"repair.class":                       {},
	"repair.domain":                      {},
	"repair.exhausted":                   {},
	"repair.feedback_keys":               {},
	"repair.field":                       {},
	"repair.final_action":                {},
	"repair.learning_hint_count":         {},
	"repair.max_attempts":                {},
	"repair.stage":                       {},
	"required_artifacts":                 {},
	"reuse_cached_result":                {},
	"reuse_session_profile":              {},
	"secondary_domains":                  {},
	"short_circuit":                      {},
	"source_tier":                        {},
	"sse.event_type":                     {},
	"target_subject":                     {},
	"task_intent":                        {},
	"time_scope":                         {},
	"tool.name":                          {},
	"tool.attempts":                      {},
	"tool.error_class":                   {},
	"tool.status":                        {},
	"top_k":                              {},
	"topic":                              {},
	"turn_type":                          {},
}

// BuildRunInspection builds the chat UI's single-turn debugging contract.
func (t *TurnTrace) BuildRunInspection() RunInspection {
	if t == nil {
		return RunInspection{Status: "error", Summary: RunSummary{InspectionText: "追踪为空，无法生成运行诊断。"}}
	}

	runtime := buildRuntimeMeta(t)
	spans := make([]RunSpan, 0, len(t.Spans))
	for _, span := range t.Spans {
		attrs := filterRunInspectionAttrs(span.Attributes)
		if span.ParentSpanID == "" && len(t.Attributes) > 0 {
			attrs = mergeAttrMaps(attrs, filterRunInspectionAttrs(t.Attributes))
			attrs = mergeAttrMaps(attrs, runtime)
		}
		spans = append(spans, RunSpan{
			SpanID:       span.SpanID,
			ParentSpanID: span.ParentSpanID,
			Name:         span.Name,
			Label:        stepLabel(span.Name),
			Kind:         string(span.Kind),
			Category:     runSpanCategory(span, attrs),
			Status:       normalizeStatus(span.Status),
			DurationMs:   span.DurationMs,
			Error:        span.Error,
			Attributes:   attrs,
		})
	}

	diagnostics := buildRunDiagnostics(t, spans)
	if diagnostics == nil {
		diagnostics = []RunDiagnostic{}
	}
	return RunInspection{
		TraceID:     t.TraceID,
		SessionID:   t.SessionID,
		Status:      normalizeStatus(t.Status),
		TurnType:    t.TurnType,
		TotalMs:     traceTotalMs(t),
		Summary:     buildRunSummary(t, runtime, diagnostics),
		Diagnostics: diagnostics,
		Spans:       spans,
	}
}

func buildRunSummary(t *TurnTrace, runtime map[string]any, diagnostics []RunDiagnostic) RunSummary {
	summary := RunSummary{}
	if v, ok := stringFromMap(runtime, "primary_domain"); ok {
		summary.PrimaryDomain = v
	}
	if v, ok := stringFromMap(runtime, "task_intent"); ok {
		summary.TaskIntent = v
	}
	if v, ok := stringFromMap(runtime, "decision_source"); ok {
		summary.DecisionSource = v
	}
	if v, ok := stringFromMap(runtime, "gate.reason"); ok {
		summary.GateReason = v
	}
	if summary.DecisionSource == "" {
		if v, ok := stringFromMap(t.Attributes, "decision_source"); ok {
			summary.DecisionSource = v
		}
	}
	if summary.GateReason == "" {
		if v, ok := stringFromMap(t.Attributes, "gate.reason"); ok {
			summary.GateReason = v
		}
	}

	if first := firstActionableDiagnostic(diagnostics); first != nil {
		summary.InspectionText = first.Title
		return summary
	}
	summary.InspectionText = "本轮运行未发现确定性异常。"
	return summary
}

func firstActionableDiagnostic(diagnostics []RunDiagnostic) *RunDiagnostic {
	for i := range diagnostics {
		if diagnostics[i].Severity == "error" {
			return &diagnostics[i]
		}
	}
	for i := range diagnostics {
		if diagnostics[i].Severity == "warn" {
			return &diagnostics[i]
		}
	}
	return nil
}

func buildRunDiagnostics(t *TurnTrace, spans []RunSpan) []RunDiagnostic {
	b := runDiagnosticBuilder{seen: map[string]struct{}{}}
	attrs := filterRunInspectionAttrs(t.Attributes)
	attrs = mergeAttrMaps(attrs, buildRuntimeMeta(t))

	if attrString(attrs, "decision_source") == "cheap_followup_reuse" {
		b.add(RunDiagnostic{
			Severity:   "info",
			Stage:      "route",
			Code:       "route.cheap_gate_reuse",
			Title:      "本轮命中 cheap gate 路由复用。",
			Evidence:   []string{"decision_source=cheap_followup_reuse"},
			NextAction: "如果领域或对象不对，优先检查 cheap gate 复用条件和上一轮执行合同。",
		})
	}
	if attrString(attrs, "failure.class") != "" || attrString(attrs, "failure.stage") != "" || attrString(attrs, "failure.code") != "" {
		b.add(RunDiagnostic{
			Severity:   "error",
			Stage:      firstNonEmptyString(attrString(attrs, "failure.stage"), "runtime"),
			Code:       "runtime.failure",
			Title:      "运行时返回结构化失败。",
			Evidence:   evidenceFromAttrs(attrs, "failure.class", "failure.stage", "failure.code", "failure.retryable", "failure.degraded"),
			NextAction: "先按 failure.stage 定位对应运行阶段，再查看同阶段 error span。",
		})
	}
	if attrString(attrs, "failure.class") == "artifact_missing" {
		b.add(artifactMissingDiagnostic("", evidenceFromAttrs(attrs, "failure.class", "failure.stage", "failure.code")))
	}
	if attrString(attrs, "failure.stage") == "final_guard" {
		b.add(guardBlockedDiagnostic("", evidenceFromAttrs(attrs, "failure.stage", "failure.code")))
	}
	if attrString(attrs, "bazi.final.audit_result") == "repaired" || attrString(attrs, "bazi.contract.recovery_policy") != "" {
		b.add(RunDiagnostic{
			Severity:   "warn",
			Stage:      "agent",
			Code:       "contract.repaired",
			Title:      "八字合同发生修复或恢复策略介入。",
			Evidence:   evidenceFromAttrs(attrs, "bazi.final.audit_result", "bazi.contract.finding_code", "bazi.contract.recovery_policy", "bazi.internal_graph.recovery_state"),
			NextAction: "查看八字内部 graph path，重点检查 validation 与 recovery_decision 节点。",
		})
	}
	if sourceEvidence := factsOnlyOrPartialEvidence(attrs); len(sourceEvidence) > 0 {
		b.add(RunDiagnostic{
			Severity:   "warn",
			Stage:      "agent",
			Code:       "contract.facts_only_or_partial",
			Title:      "八字输出包含 facts-only、partial 或 degraded 来源。",
			Evidence:   sourceEvidence,
			NextAction: "优先检查 static/dynamic synthesis 的合同错误与证据覆盖。",
		})
	}

	for _, span := range spans {
		if span.Status == "error" || strings.TrimSpace(span.Error) != "" {
			b.add(RunDiagnostic{
				Severity:   "error",
				Stage:      stageForRunSpan(span),
				Code:       "span.error",
				Title:      fmt.Sprintf("%s 步骤失败。", span.Label),
				Evidence:   compactEvidence([]string{fmt.Sprintf("span=%s", span.Name), fmt.Sprintf("status=%s", span.Status), errorEvidence(span.Error)}),
				NextAction: "打开该 span 详情查看 error 与白名单 attributes。",
				SpanID:     span.SpanID,
			})
		}
		if value, ok := boolAttr(span.Attributes, "artifact_present"); ok && !value {
			b.add(artifactMissingDiagnostic(span.SpanID, evidenceFromAttrs(span.Attributes, "artifact_present")))
		}
		if attrString(span.Attributes, "guardrail_result") == "blocked" {
			b.add(guardBlockedDiagnostic(span.SpanID, evidenceFromAttrs(span.Attributes, "guardrail_result")))
		}
		if span.Category == "retriever" && attrInt(span.Attributes, "hits") == 0 {
			b.add(RunDiagnostic{
				Severity:   "warn",
				Stage:      "retrieval",
				Code:       "retrieval.no_hits",
				Title:      "知识检索没有命中结果。",
				Evidence:   evidenceFromAttrs(span.Attributes, "query", "hits"),
				NextAction: "检查检索关键词、知识库服务和必需主题覆盖。",
				SpanID:     span.SpanID,
			})
		}
	}
	return b.items
}

type runDiagnosticBuilder struct {
	items []RunDiagnostic
	seen  map[string]struct{}
}

func (b *runDiagnosticBuilder) add(d RunDiagnostic) {
	key := d.Code + "|" + d.SpanID
	if _, ok := b.seen[key]; ok {
		return
	}
	b.seen[key] = struct{}{}
	b.items = append(b.items, d)
}

func artifactMissingDiagnostic(spanID string, evidence []string) RunDiagnostic {
	return RunDiagnostic{
		Severity:   "error",
		Stage:      "prepare",
		Code:       "artifact.missing",
		Title:      "主领域所需资产缺失。",
		Evidence:   evidence,
		NextAction: "检查 ExecutionPlan 的 required artifacts 与 prefill/tool runner 实际产出是否一致。",
		SpanID:     spanID,
	}
}

func guardBlockedDiagnostic(spanID string, evidence []string) RunDiagnostic {
	return RunDiagnostic{
		Severity:   "error",
		Stage:      "guard",
		Code:       "guard.blocked",
		Title:      "最终输出被 guard 阻断。",
		Evidence:   evidence,
		NextAction: "检查 final guard 前的主领域资产和最终文本边界。",
		SpanID:     spanID,
	}
}

func filterRunInspectionAttrs(src map[string]any) map[string]any {
	if len(src) == 0 {
		return nil
	}
	keys := make([]string, 0, len(src))
	for key := range src {
		if _, ok := runInspectionAttrWhitelist[key]; ok {
			keys = append(keys, key)
		}
	}
	if len(keys) == 0 {
		return nil
	}
	sort.Strings(keys)
	out := make(map[string]any, len(keys))
	for _, key := range keys {
		out[key] = src[key]
	}
	return out
}

// traceTotalMs returns the whole-turn duration while the trace may still be open.
func traceTotalMs(t *TurnTrace) int64 {
	if t == nil {
		return 0
	}
	var totalMs int64
	if !t.EndedAt.IsZero() {
		totalMs = t.EndedAt.Sub(t.StartedAt).Milliseconds()
	} else {
		totalMs = time.Since(t.StartedAt).Milliseconds()
	}
	if totalMs < 0 {
		return 0
	}
	return totalMs
}

// normalizeStatus keeps empty span statuses displayable in the inspector.
func normalizeStatus(status string) string {
	if status == "" {
		return "ok"
	}
	return status
}

// buildRuntimeMeta extracts the manager-owned execution contract for the root span.
func buildRuntimeMeta(t *TurnTrace) map[string]any {
	snapshot, ok := executionSnapshotFromTrace(t)
	if !ok || snapshot == nil {
		return nil
	}
	meta := map[string]any{}
	if snapshot.PrimaryDomain != "" {
		meta["primary_domain"] = snapshot.PrimaryDomain
	}
	if len(snapshot.Domains) > 0 {
		meta["domains"] = snapshot.Domains
	}
	if len(snapshot.SecondaryDomains) > 0 {
		meta["secondary_domains"] = snapshot.SecondaryDomains
	}
	if snapshot.TaskIntent != "" {
		meta["task_intent"] = snapshot.TaskIntent
	}
	if snapshot.ConversationIntent != "" {
		meta["conversation_intent"] = snapshot.ConversationIntent
	}
	if len(snapshot.RequiredArtifacts) > 0 {
		meta["required_artifacts"] = snapshot.RequiredArtifacts
	}
	if snapshot.FollowupMode != "" {
		meta["followup_mode"] = snapshot.FollowupMode
	}
	if snapshot.NeedsClarification {
		meta["needs_clarification"] = true
	}
	if snapshot.QimenMode != "" {
		meta["qimen_mode"] = snapshot.QimenMode
	}
	if snapshot.TargetSubject != "" {
		meta["target_subject"] = snapshot.TargetSubject
	}
	if snapshot.TimeScope != "" {
		meta["time_scope"] = snapshot.TimeScope
	}
	if snapshot.Gate.ExecutionMode != "" {
		meta["gate.execution_mode"] = snapshot.Gate.ExecutionMode
	}
	if snapshot.Gate.Reason != "" {
		meta["gate.reason"] = snapshot.Gate.Reason
	}
	if snapshot.Gate.FollowupPolicy != "" {
		meta["gate.followup_policy"] = snapshot.Gate.FollowupPolicy
	}
	if snapshot.Gate.ReuseCachedResult {
		meta["reuse_cached_result"] = true
	}
	if snapshot.Gate.ReuseSessionProfile {
		meta["reuse_session_profile"] = true
	}
	if snapshot.Gate.Reason == "cheap_followup_reuse" {
		meta["decision_source"] = "cheap_followup_reuse"
	}
	if len(meta) == 0 {
		return nil
	}
	return meta
}

func mergeAttrMaps(dst map[string]any, src map[string]any) map[string]any {
	if len(src) == 0 {
		return dst
	}
	if dst == nil {
		dst = map[string]any{}
	}
	for key, value := range src {
		dst[key] = value
	}
	return dst
}

func runSpanCategory(span TraceSpan, attrs map[string]any) string {
	name := strings.ToLower(span.Name)
	switch {
	case strings.Contains(name, "contract_gate") || strings.Contains(name, "final_guard"):
		return "guard"
	case name == "sse_emit":
		return "sse"
	case strings.HasPrefix(name, "bazi_") || hasBaziAttr(attrs):
		return "bazi_graph"
	}
	switch span.Kind {
	case KindLLM:
		return "llm"
	case KindTool:
		return "tool"
	case KindRetriever:
		return "retriever"
	case KindAgent:
		return "agent"
	default:
		return "chain"
	}
}

func hasBaziAttr(attrs map[string]any) bool {
	for key := range attrs {
		if strings.HasPrefix(key, "bazi.") {
			return true
		}
	}
	return false
}

func stageForRunSpan(span RunSpan) string {
	switch span.Category {
	case "retriever":
		return "retrieval"
	case "guard":
		return "guard"
	case "bazi_graph", "llm":
		return "agent"
	case "tool":
		return "prepare"
	case "sse":
		return "runtime"
	default:
		return "runtime"
	}
}

func factsOnlyOrPartialEvidence(attrs map[string]any) []string {
	return compactEvidence([]string{
		factsOnlyOrPartialValue(attrs, "bazi.static.source"),
		factsOnlyOrPartialValue(attrs, "bazi.dynamic.source"),
		factsOnlyOrPartialValue(attrs, "bazi.final.output_mode"),
	})
}

func factsOnlyOrPartialValue(attrs map[string]any, key string) string {
	value := attrString(attrs, key)
	if value == "" {
		return ""
	}
	lower := strings.ToLower(value)
	for _, marker := range []string{"facts", "fact", "partial", "degraded"} {
		if strings.Contains(lower, marker) {
			return key + "=" + value
		}
	}
	return ""
}

func evidenceFromAttrs(attrs map[string]any, keys ...string) []string {
	evidence := make([]string, 0, len(keys))
	for _, key := range keys {
		if value, ok := attrs[key]; ok {
			evidence = append(evidence, fmt.Sprintf("%s=%v", key, value))
		}
	}
	return evidence
}

func compactEvidence(values []string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value != "" {
			out = append(out, value)
		}
	}
	return out
}

func errorEvidence(err string) string {
	if strings.TrimSpace(err) == "" {
		return ""
	}
	return "error=" + err
}

func stringFromMap(attrs map[string]any, key string) (string, bool) {
	value := attrString(attrs, key)
	return value, value != ""
}

func attrString(attrs map[string]any, key string) string {
	if len(attrs) == 0 {
		return ""
	}
	value, ok := attrs[key]
	if !ok || value == nil {
		return ""
	}
	if s, ok := value.(string); ok {
		return strings.TrimSpace(s)
	}
	return strings.TrimSpace(fmt.Sprint(value))
}

func attrInt(attrs map[string]any, key string) int {
	value, ok := attrs[key]
	if !ok {
		return -1
	}
	switch v := value.(type) {
	case int:
		return v
	case int64:
		return int(v)
	case float64:
		return int(v)
	case float32:
		return int(v)
	default:
		return -1
	}
}

func boolAttr(attrs map[string]any, key string) (bool, bool) {
	value, ok := attrs[key]
	if !ok {
		return false, false
	}
	v, ok := value.(bool)
	return v, ok
}

func firstNonEmptyString(values ...string) string {
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			return value
		}
	}
	return ""
}
